#ifndef PLAINDOCUMENT_IDL
#define PLAINDOCUMENT_IDL

#include "idocument.idl"

interface PlainDocument: IDocument {
  // Associations
  // Attributes
  private attribute Controller controller;
  private attribute Model model;
  // Operations
  Controller getController (  );
  Model getModel (  );
  String serialize (  );
  void close (  );
};

#endif
