#include "nsISupports.idl"
#include "nsIURI.idl"

[scriptable, uuid(DF37977D-DE29-498B-8C1D-235F8DFA5673)]
interface wyIYulupSitetreeView : nsISupports
{
  nsIURI getCurrentCollectionURI();

  nsIURI getCurrentResourceURI();
};
