#include "nsISupports.idl"
#include "wyIYulupProtocol.idl"

[scriptable, uuid(06396D77-2570-446D-8CB7-400339FF349C)]
interface wyIYulupService : nsISupports
{
  void init();

  void registerProtocol(in wyIYulupProtocol aYulupProtocol);
};
